language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: GzdjK4wNwEwIyStjctf0hq1ll31uJmkkPzd46rt/RFZtoqRaukOPdETt3d7zq4nMUebpcHP+dMMzvUAHHhdlP6m30J2K998UKEO3gFjsk1b8S6kySkmHusYDcYehIVow89dPNDBdvfQTCXVa+8lEnflamLnnnZMDW7PddCEMj2asrxMa1kfGevE0uAx5q/RFh+sdY2ISVjQ9c3XGSgn9P1l8KlGizV1T+0ohC/OFdYfiXI7ARA3IKDtRpYE+5Q4WbNAaQ9voxxYCYW8UdKxmDhbvYf0w6U1WbFBjPmh+u3BwURmkwoSnE95Rk4qDNMvH4ag0MLecmlccRBYzxNC8vvBwy2/HLLJ/GxXpCniQ4kEXHL+nUwRFuK2FOd+xfP4r7ARQUrDKwAcANkaHQOqX3n8xiVMGr5ElPY5Ap6rqgNrz6m874Lf6RPGzpVOHTFvJNHDuB6FDL4hVgj/j2mtQ8tUtub0buFj57gOzNBBz+w1ZtfcrRgEsbURkV7grKK8F6kthjSKU65dIqDj1eMAedH8L2qjSQYmLj10kO6W7fO86YtcRjveT7FJyg1hKub7y1MjCZNXQw4b28p9Kmo9NqBzJ6WxIhpcoHPvaBfY3KViHmr9/iden7Jak3MHS+wCeqxxPV0UKj5TbBZ927r/9Gl6Osg8eTnoD8tMW3WazoVo=
